apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozserver-deployment
  labels:
    app: cozserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cozserver
  template:
    metadata:
      labels:
        app: cozserver
    spec:
      containers:
      - name: cozserver
        image: sebcontents/cozserver:1.0
        ports:
        - containerPort: 80
