apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-cozserver
spec:
  replicas: 3
  selector:
      app: cozserver  # cozserver 1개 보장해주란 의미
  template:
    metadata:
      name: cozserver-pod
      labels:
        app: cozserver #selector의 라벨과 동일해야함.
    spec:
      containers:
      - name: cozserver
        image: sebcontents/cozserver:1.0
